###################################
# PETICIONES PARA LA TABLA MOVIES #
###################################


###
POST http://localhost:9000/api/movies HTTP/1.1
Content-Type: application/json

{
    "mov_id": 2,
    "mov_title": "Avatar",
    "mov_year": 2008,
    "mov_time": 180,
    "mov_lang": "ENG",
    "mov_dt_rel": "09-18-2008",
    "mov_rel_country": "USA"
}


###
GET http://localhost:9000/api/movies  HTTP/1.1


###
GET http://localhost:9000/api/movies/1 HTTP/1.1


###
PUT http://localhost:9000/api/movies/1 HTTP/1.1
Content-Type: application/json

{
    
    "mov_id": 1,
    "mov_title": "Avatar",
    "mov_year": 2008,
    "mov_time": 190,
    "mov_lang": "ENG",
    "mov_dt_rel": "09-18-2008",
    "mov_rel_country": "USA"
}


###
DELETE http://localhost:9000/api/movies/1 HTTP/1.1


###################################
# PETICIONES PARA LA TABLA ACTORS #
###################################


###
POST http://localhost:9000/api/actors HTTP/1.1
Content-Type: application/json

{

    "act_id": 2,
    "act_fname": "Ben",
    "act_lname": "Aflek",
    "act_gender": "M"

}


###
GET http://localhost:9000/api/actors  HTTP/1.1


###
GET http://localhost:9000/api/actors/1 HTTP/1.1


###
PUT http://localhost:9000/api/actors/1 HTTP/1.1
Content-Type: application/json

{
    
    "act_id": 1,
    "act_fname": "Jhorge",
    "act_lname": "Clouni",
    "act_gender": "M"
}


###
DELETE http://localhost:9000/api/actors/3 HTTP/1.1


######################################
# PETICIONES PARA LA TABLA DIRECTORS #
######################################


###
POST http://localhost:9000/api/directors HTTP/1.1
Content-Type: application/json

{
    "dir_id": 4,
    "dir_fname": "Juan",
    "dir_lname": "Torres"
    
}


###
GET http://localhost:9000/api/directors  HTTP/1.1


###
GET http://localhost:9000/api/directors/1 HTTP/1.1


###
PUT http://localhost:9000/api/directors/4 HTTP/1.1
Content-Type: application/json

{
    
   "dir_id": 3,
    "dir_fname": "Juan",
    "dir_lname": "Torrez"
}


###
DELETE http://localhost:9000/api/directors/4 HTTP/1.1


######################################
# PETICIONES PARA LA TABLA MOVIECAST #
######################################


###
POST http://localhost:9000/api/movie_cast HTTP/1.1
Content-Type: application/json

{
    "act_id": 3,
    "mov_id": 1,
    "role": "carpintero"
    
}


###
GET http://localhost:9000/api/movie_cast  HTTP/1.1


###
GET http://localhost:9000/api/movie_cast/2 HTTP/1.1


###
PUT http://localhost:9000/api/movie_cast/1 HTTP/1.1
Content-Type: application/json

{
    
  "act_id": 1,
    "mov_id": 1,
    "role": "mesero"
}


###
DELETE http://localhost:9000/api/movie_cast/3 HTTP/1.1


###########################################
# PETICIONES PARA LA TABLA MOVIEDIRECTION #
###########################################


###
POST http://localhost:9000/api/movie_direction HTTP/1.1
Content-Type: application/json

{
    "dir_id": 3,
    "mov_id": 3
    
}


###
GET http://localhost:9000/api/movie_direction  HTTP/1.1


###
GET http://localhost:9000/api/movie_direction/2 HTTP/1.1


###
PUT http://localhost:9000/api/movie_direction/1 HTTP/1.1
Content-Type: application/json

{
    
    "dir_id": 1,
    "mov_id": 3
}


###
DELETE http://localhost:9000/api/movie_direction/3 HTTP/1.1
